MVCProject/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDBEntities : DbContext
    {
        public ProjectDBEntities()
            : base("name=ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_customer> tbl_customer { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
    }
}

MVCProject/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'c:\users\nexwave\documents\visual studio 2015\Projects\MVCProject\MVCProject\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVCProject/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVCProject/Models/tbl_customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public tbl_customer()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int customerId { get; set; }
        public string customerName { get; set; }
    
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}

MVCProject/Models/tbl_order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int orderId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> customerId { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
    }
}

MVCProject/Controllers/OrderCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;
namespace MVCProject.Controllers
{
    public class OrderCRUDController : Controller
    {
        ProjectDBEntities db = new ProjectDBEntities();
        [HttpGet]
        public ActionResult AddOrder()
        {
            var data = new SelectList(db.tbl_customer, "customerId", "customerName");
            Session["sdata"] = data;
            return View();
        }
        [HttpPost]
        public ActionResult AddOrder(string command)
        {
            if (command == "Insert")
            {
                tbl_order obj = new tbl_order();
                obj.productName = Request.Form["txtpname"].ToString();
                obj.price = decimal.Parse(Request.Form["txtprice"].ToString());
                obj.customerId = int.Parse(Request.Form["ddlname"].ToString());
                db.tbl_order.Add(obj);
                var result = db.SaveChanges();
                if (result > 0)
                {
                    ModelState.AddModelError("", "Order Placed Successfully");
                    return View();
                }
                else
                {
                    ModelState.AddModelError("", "Technical Error Occured:Unable to Place Order !");
                    return View();
                }
            }
            else
            {
                
                return View();
            }
        }
        [HttpGet]
        public ActionResult GetOrderByCustomer()
        {
            var data = new SelectList(db.tbl_customer, "customerId", "customerName");
            Session["sdata"] = data;
            return View();
        }
        [HttpPost]
        public ActionResult GetOrderByCustomer(string command)
        {
            int custid = int.Parse(Request.Form["ddlid"].ToString());
            if (command == "Search")
            {
                var data = (from t in db.tbl_order
                            where t.customerId == custid
                            select t).ToList();
                Session["pdata"] = data;
                return View();
            }
            return View();
        }
        [HttpGet]
        public ActionResult GetOrderByID()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetOrderByID(string command)
        {
            int custid = int.Parse(Request.Form["txtid"].ToString());
            if (command == "Search")
            {
                var data = (from t in db.tbl_order
                            where t.customerId == custid
                            select t).ToList();
                Session["pdata"] = data;
                return View();
            }
            return View();
        }
        [HttpGet]
        public ActionResult ChangeOrderPrice(int id)
        {
            var data = (from t in db.tbl_order
                        where t.orderId == id
                        select t).SingleOrDefault();
            Session["udata"] = data;
            return View();
        }
        [HttpPost]
        public ActionResult ChangeOrderPrice()
        {
            int id = int.Parse(Request.Form["txtid"].ToString());
            var olddata = db.tbl_order.Where(x => x.orderId == id).SingleOrDefault();
            olddata.price = decimal.Parse(Request.Form["txtprice"].ToString());
            var res = db.SaveChanges();
            if (Session["check"].ToString() == "customer")
                return RedirectToAction("GetOrderByCustomer");
            else
                return RedirectToAction("GetOrderByID");

        }
        [HttpGet]
        public ActionResult Homepage()
        {
            return View();
        }
    }
}

MVCProject/Views/OrderCRUD/AddOrder.cshtml
@{
    ViewBag.Title = "AddOrder";
}

<h2 style="text-align:center" >Place Order</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div style="background-color:white;height:400px;width:auto">
        <br />
        <br />
        <table border="1" align="center" cellpadding="15" style="font-family:'Berlin Sans FB';font-size:large;border-width:2px">
            <tr style="background-color:darkgray">
                <th colspan="2" align="center" style="color:lightskyblue">Input Order</th>
            </tr>
            <tr>
                <td>Product Name:</td>
                <td>@Html.TextBox("txtpname")</td>
            </tr>
            <tr>
                <td>Price:</td>
                <td>@Html.TextBox("txtprice")</td>
            </tr>
            <tr>
                <td>Customer:</td>
                <td>@Html.DropDownList("ddlname",Session["sdata"] as SelectList) </td>
            </tr>
            <tr>
                <td><input type="submit" value="Cancel" name="command"/></td>
                <td><input type="submit" value="Insert" name="command"/></td>
            </tr>
        </table>
    </div>
}

MVCProject/Views/OrderCRUD/ChangeOrderPrice.cshtml
@model IEnumerable<MVCProject.Models.ProjectDBEntities>
@{
    ViewBag.Title = "ChangeOrderPrice";
}

<h2>ChangeOrderPrice</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    if (Session["udata"]!= null)
    {
        MVCProject.Models.tbl_order obj = (MVCProject.Models.tbl_order)Session["udata"];
        <table>
            <tr>
                <th>Modify Order Details</th>
            </tr>
            <tr>
                <td>Order ID :</td>
                <td><input type="text" id="txtid" name="txtid" value="@obj.orderId" readonly/></td>
            </tr>
            <tr>
                <td>Product Name :</td>
                <td><input type="text" id="txtname" name="txtname" value="@obj.productName" readonly /></td>
            </tr>
            <tr>
                <td>Price :</td>
                <td><input type="text" id="txtprice" name="txtprice" value="@obj.price"  /></td>
            </tr>
            <tr>
                <td><input type="submit" value="Update" name="command" /></td>
            </tr>
        </table>
    }
    else
    {
        <table><tr><td>Error:</td></tr></table>
    }
}

MVCProject/Views/OrderCRUD/GetOrderByCustomer.cshtml
@model IEnumerable<MVCProject.Models.ProjectDBEntities>
@{
    ViewBag.Title = "GetOrderByCustomer";
}

<h2 style="text-align:center">Search Order By Customer Name</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div style="background-color:white;height:auto;width:auto">
        <table align="center" cellpadding="10">
            <tr>
                <td>Select Name:</td>
                <td>@Html.DropDownList("ddlid", Session["sdata"] as SelectList)</td>
                <td><input type="submit" value="Search" name="command" /></td>
            </tr>
        </table>
    </div>
    <div style="background-color:white;height:auto;width:auto">
        <table align="center" cellpadding="10">
            @if (Session["pdata"] != null)
            {
                List<MVCProject.Models.tbl_order> pname = (List<MVCProject.Models.tbl_order>)Session["pdata"];
                Session["check"] = "customer";
                foreach (var p in pname)
                {
                    <tr>
                        <td>@Html.ActionLink(@p.productName, "ChangeOrderPrice", new { Id = @p.orderId.ToString() })</td>
                    </tr>
                }

            }
        </table>
    </div>
}

MVCProject/Views/OrderCRUD/GetOrderByID.cshtml
@model IEnumerable<MVCProject.Models.ProjectDBEntities>
@{
    ViewBag.Title = "GetOrderByCustomer";
}

<h2 style="text-align:center">Search Order By Customer ID</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div style="background-color:white;height:auto;width:auto">
        <table align="center" cellpadding="10">
            <tr>
                <td>Enter Customer ID:</td>
                <td><input type="number" name="txtid" id="txtid" /></td>
                <td><input type="submit" value="Search" name="command" /></td>
            </tr>
        </table>
    </div>
    <div style="background-color:white;height:auto;width:auto">
        <table align="center" cellpadding="10">
            @if (Session["pdata"] != null)
            {
                List<MVCProject.Models.tbl_order> pname = (List<MVCProject.Models.tbl_order>)Session["pdata"];
                Session["check"] = "id";
                foreach (var p in pname)
                {
                    <tr>
                        <td>@Html.ActionLink(@p.productName, "ChangeOrderPrice", new { Id = @p.orderId.ToString() })</td>
                    </tr>
                }

            }
        </table>
    </div>
}

MVCProject/Views/OrderCRUD/Homepage.cshtml
@{
    ViewBag.Title = "Homepage";
}

<h2 style="text-align:center;font-size:x-large">Visual Super Marker</h2>
<br />
<div style="background-color:white;height:auto;width:auto">
    <table align="center" cellpadding="10">
        <tr>
            <td>Welcome to Visual SuperMarket Where There is a Solution For Every Needs</td>

        </tr>
        <tr>
            <td>Successful For the past 15 Years!!</td>
        </tr>
        </table>
</div>

MVCProject/Views/Shared/MasterView.cshtml
<div style="background-color:gainsboro;color:red;text-align:center;font-family:Arial;font-size:large;width:auto;height:50px">
    <h1>Order Details</h1>
</div>
<div style="background-color:gainsboro;color:red;text-align:center;font-family:Arial;font-size:large;width:auto;height:50px">
    <table cellpadding="10" align="center">
        <tr style="text-align:center">
            <td>@Html.ActionLink("Place Order", "AddOrder", "OrderCRUD")</td>
            <td>@Html.ActionLink("Search By Customer Name", "GetOrderByCustomer", "OrderCRUD")</td>
            <td>@Html.ActionLink("Select By ID", "GetOrderByID", "OrderCRUD")</td>
            <td>@Html.ActionLink("Home Page","Homepage","OrderCRUD")</td>
        </tr>
    </table>
</div>
<div style="background-color:aliceblue">
    @RenderBody()
</div>

MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>